/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReagentsRouteImport } from './routes/reagents'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorsIndexRouteImport } from './routes/calculators.index'
import { Route as CalculatorsSlugRouteImport } from './routes/calculators.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReagentsRoute = ReagentsRouteImport.update({
  id: '/reagents',
  path: '/reagents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsIndexRoute = CalculatorsIndexRouteImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSlugRoute = CalculatorsSlugRouteImport.update({
  id: '/calculators/$slug',
  path: '/calculators/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/planner': typeof PlannerRoute
  '/protocols': typeof ProtocolsRoute
  '/reagents': typeof ReagentsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/calculators/$slug': typeof CalculatorsSlugRoute
  '/calculators/': typeof CalculatorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/planner': typeof PlannerRoute
  '/protocols': typeof ProtocolsRoute
  '/reagents': typeof ReagentsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/calculators/$slug': typeof CalculatorsSlugRoute
  '/calculators': typeof CalculatorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/planner': typeof PlannerRoute
  '/protocols': typeof ProtocolsRoute
  '/reagents': typeof ReagentsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/calculators/$slug': typeof CalculatorsSlugRoute
  '/calculators/': typeof CalculatorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assistant'
    | '/auth'
    | '/history'
    | '/planner'
    | '/protocols'
    | '/reagents'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/chat'
    | '/calculators/$slug'
    | '/calculators/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assistant'
    | '/auth'
    | '/history'
    | '/planner'
    | '/protocols'
    | '/reagents'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/chat'
    | '/calculators/$slug'
    | '/calculators'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assistant'
    | '/auth'
    | '/history'
    | '/planner'
    | '/protocols'
    | '/reagents'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/chat'
    | '/calculators/$slug'
    | '/calculators/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  PlannerRoute: typeof PlannerRoute
  ProtocolsRoute: typeof ProtocolsRoute
  ReagentsRoute: typeof ReagentsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  CalculatorsSlugRoute: typeof CalculatorsSlugRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reagents': {
      id: '/reagents'
      path: '/reagents'
      fullPath: '/reagents'
      preLoaderRoute: typeof ReagentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/calculators'
      fullPath: '/calculators/'
      preLoaderRoute: typeof CalculatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/$slug': {
      id: '/calculators/$slug'
      path: '/calculators/$slug'
      fullPath: '/calculators/$slug'
      preLoaderRoute: typeof CalculatorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  PlannerRoute: PlannerRoute,
  ProtocolsRoute: ProtocolsRoute,
  ReagentsRoute: ReagentsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  CalculatorsSlugRoute: CalculatorsSlugRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
